languageCode: "en"
defaultContentLanguage: "en"
title: "@thisisobate"
theme: "KeepIt"
publishDir: "public"

enableRobotsTXT: true
googleAnalytics: G-240P1M22G1

sitemap:
  changefreq: "monthly"
  filename: "sitemap.xml"
  priority: 0.5

paginate: 12
enableEmoji: true
canonifyURLs: true
blackfriday:
  hrefTargetBlank: true
  nofollowLinks: true
  noreferrerLinks: true

permalinks:
  posts: "/:year/:filename/"

menu:
  main:
  - name: "Blog"
    url: "/posts/"
    weight: 1
  - name: "About me"
    url: "/about/"
    weight: 2

params:
  since: 2020
  author: "Uchechukwu Obasi"
  avatar: "/images/uche_obasi.jpg"
  socialShare: true
  subtitle: true
  cdn_url: "" # Base CDN URL
  description: "💪💻🏐"
  keywords: "uche obasi"
  license: 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  social:
    GitHub: "thisisobate"
    Linkedin: "thisisobate"
    Twitter: "thisisobate"
    Youtubecustom: "@thisisobate"
    Email: "obasiuche62@gmail.com"
  share:
    Twitter: true
    Facebook: true
    Linkedin: true

author:
  name: "@thisisobate"
  params:
    publisher:
      name: "thisisobate"
      logo:
        url: "/images/uche_obasi.jpg"
        width: 127
        height: 40
    logo:
      url: "/images/uche_obasi.jpg"
      width: 127
      height: 40
    image:
      url: "/images/uche_obasi.jpg"
      width: 127
      height: 40

# Used only for Seo schema.
copyright: "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."